language: shell

env:
  - RELEASE_FOLDER=./releases

addons:
  apt:
    packages:
    - luarocks

install: luarocks install --local luacheck
before_script:
  - lua gen_option_values.lua
  - "/home/travis/.luarocks/bin/luacheck . -q"
script: curl -s https://raw.githubusercontent.com/Avyiel/packager/master/release.sh | bash -s -- -d -r $RELEASE_FOLDER

deploy:
  provider: releases
  token:
    secure: NbOQUhFtm2EismtJ/2jTMtpTCTdBtEcFrxZE2GZydVKsGuxfEuk+WPmI81qmLtuhi6W0gP7ULg9IVlPxOA9RpfTPQArC9MV1wTmyIng8BzIB26fOFOgBpWPkcHopiX/J+876U5cuU/hYM73T1laAeR35w7lP5DlmRRWZRSiBO+Ba2mFvXiehKPXD6qkJuJ2a1dRW7jKKxpAw0eqNPtaZhmZh8yYuSjdYAbPtKEmncE2ka/wxdfLK3xI/Gy87lVTr9rAVJpvcFVWJZXU3AhOUOH6WLo0H3bNZIgbM0aGh3Sni2vkySKsYcHEJU0sfN22Xp9dw2YopNOX9C1WKWP6RfHar+KRnMm0QKFaUblYwe3hHCRqp9bbPfelOu/NQNF9vY8kXO3rJ/XPKmTvq1YCsLIn02LKS4n1e5ccDHUzaw8iCxtQNrfUukRLK1HyVmEC59jjqhf38BFn/gnM6BmC3Dju6WeYsx7JfH2lz28E2uobHiMDdu3pAa0mCfYF9eKXMoHmjpk6MH/wcuVY5UO84MPbp4+Bvfvq7pUbvgHa7hAGmuzCFtlokd9t8zLl4aTzNiL9f7/guuPVs0YdR0nQTHuyceAGBxlMfld4NXPWgtJXhHXTHZTIPbcGc52GRMIvRw6GgKYkR6y4ypfY2vj7C1KTpzssyQYJgEhelTgqWFbA=
  cleanup: false
  file_glob: true
  file: $RELEASE_FOLDER/BigWigs*.zip
  on:
    branch: custom
    tags: true

notifications:
  email:
    on_success: never
    on_failure: always
